import { getFirestore, collection, addDoc } from 'firebase/firestore';
import { app } from './firebaseConfig'; // Ensure your firebase configuration (app) is exported from a separate file

// Initialize Firestore
const db = getFirestore(app);

/**
 * Adds the provided idData object to the 'idData' collection in Firestore.
 * @param idData Object containing ID details.
 * @returns The document ID generated by Firestore.
 */
export async function addIdDataToFirestore(idData: any): Promise<string> {
    try {
        const docRef = await addDoc(collection(db, 'idData'), idData);
        console.log('Document written with ID: ', docRef.id);
        return docRef.id;
    } catch (error) {
        console.error('Error adding document: ', error);
        throw error;
    }
}
